### ISSUE TITLE
Zod: Doesn't create Array only Object

### ISSUE THREAD

**Issue by jamalsoueidan** [anymaniax/orval#1030]
## What are the steps to reproduce this issue?

```yaml
type: array
items:
  type: object
  properties:
    day:
      $ref: ../../_types/day.yaml
    intervals:
      type: array
      items:
        $ref: ../../_types/interval.yaml

  required:
    - day
    - intervals
```

## What happens?

It doesn't create the zod definition, only if it start with object.

## What were you expecting to happen?

to create the zod object:

```js
export const test= zod.array({
  ...
});
```
