### ISSUE TITLE
Receiving Type = never when using a discriminator

### ISSUE THREAD

**Issue by SHergibo** [anymaniax/orval#1260]
## What are the steps to reproduce this issue?

1. Use the yaml file provided in this issue
2. Use Orval to generate the endpoints/types/... 

## What happens?

Some types are translated to `never` when generating a spec api which has a schema with a discriminator.

<img width="359" alt="Screenshot 2024-03-13 at 15 25 50" src="https://github.com/anymaniax/orval/assets/39282300/fa18da86-59c6-4d02-83ae-1144e3af92e2">

## What were you expecting to happen?

I expected to receive the correct type instead of `never`.

## Any logs, error output, etc?

Here is a minimal version of a spec api with a discriminator where the types `ProfessionalSession` and `SysAdminSession` are translated to `never`.

[discriminator_spec.yml.zip](https://github.com/anymaniax/orval/files/14589069/discriminator_spec.yml.zip)

Schema where we use the discriminator (check the yml file to have a global view of my spec).

```
Session:
      type: object
      required:
        - sessionType
      properties:
        sessionType:
          $ref: '#/components/schemas/SessionType'
      discriminator:
        propertyName: sessionType
        mapping:
          ProfessionalSession: '#/components/schemas/ProfessionalSession'
          SysAdminSession: '#/components/schemas/SysAdminSession'
```
## Any other comments?

I think the problem comes from this intersection in the type `ProfessionalSession`, if I delete it, the type is correctly set.

`& {
    sessionType: ProfessionalSessionSessionType;
  }`

Correct Type without the intersection `sessionType`:

<img width="565" alt="Screenshot 2024-03-13 at 15 58 19" src="https://github.com/anymaniax/orval/assets/39282300/3194a93a-c064-4915-82a6-b8e6420f5b12">

I don't know if that will help but this problem comes from an update of Orval to the version 6.25.0. Before this update we were at the version 6.7.1 (yes I know it's an old version).

The type was like that when we were using the version 6.7.1

```
export type ProfessionalSession = Session & ProfessionalSessionAllOf;
```

And the type is now like that with the version 6.25.0

```
export type ProfessionalSession = Session &
  ProfessionalSessionAllOf & {
    sessionType: ProfessionalSessionSessionType;
  };
```

## What versions are you using?

**Operating System:** macOS Sonoma Version 14.2.1
**Package Version:** Orval version 6.25.0
**Browser Version:** Google Chrome Version 122.0.6261.112 (Official Build) (x86_64)

**Comment by AffeJonsson** [comment]
Changing the spec in the session component from
```
discriminator:
  propertyName: sessionType
  mapping:
    ProfessionalSession: '#/components/schemas/ProfessionalSession'
    SysAdminSession: '#/components/schemas/SysAdminSession'
```
to
```
discriminator:
  propertyName: sessionType
  mapping:
    Professional: '#/components/schemas/ProfessionalSession'
    SysAdmin: '#/components/schemas/SysAdminSession'
```
Solves the issue. I haven't got the best knowledge about discriminators, but to me it makes sense that the keys in mapping of an enum type should match the enum values?
