### ISSUE TITLE
[Feature]Enable `faker.helpers.fromRegExp()` to be applied to msw mock from pattern keyword 

### ISSUE THREAD

**Issue by mmrakt** [anymaniax/orval#1396]
## What are the steps to reproduce this issue?

I would like to be able to apply `faker.helpers.fromRegExp()` to msw mock from a `pattern`keyword.

e.g.

```yml
schemas:
  userId:
    description: user ID
    type: string
    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}$'
    example: '1579f37a-a3e1-201d'
 userName:
    description: user name
    type: string
    example: 'john doe' 
```

The current situation is converted as follows.

```ts
uesrId: faker.word.sample(),
uesrName: faker.word.sample()
```

I want it converted as follows.

```ts
userId: faker.helpers.fromRegExp(/[0-9a-f]{8}-[0-9a-f]{4}/), // e43d7650-d266
uesrName: faker.word.sample()
```

Or if you have an alternative, I'd love to hear about it!

## What happens?

…

## Any other comments?

…

## What versions are you using?

**Operating System:** …
**Package Version:** …
**Browser Version:** …
