### ISSUE TITLE
Add dependabot support

### ISSUE THREAD

**Issue by melloware** [anymaniax/orval#306]
For keeping your dependencies up to date and security checks.

Just add this `dependabot.yml` file in your `.github` directory.

```yaml
version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```
