### ISSUE TITLE
Bug: parameter names identical to js keywords are not prefixed

### ISSUE THREAD

**Issue by yekver** [anymaniax/orval#350]
```
/method/{default}:
    get:
      parameters:
        - name: default
```

Ends up with `Declaration or statement expected.ts(1128)` in generated file. Because parameter name `default` is not prefixed with `_`
