### ISSUE TITLE
Additional properties causing TS error. "Property is not assignable to index type."

### ISSUE THREAD

**Issue by Tymek** [anymaniax/orval#600]
### What are the steps to reproduce this issue?

Create schema with typed `additionalProperties`
```
        "additionalProperties": {
          "type": "string",
          "example": "something"
        },
```

### Discussed in https://github.com/anymaniax/orval/discussions/599

<div type='discussions-op-text'>

<sup>Originally posted by **Tymek** September 30, 2022</sup>
When I have additional properties (like in **[this source file](https://github.com/Unleash/unleash/blob/9ba441b9cf63dbca4b394dc95571eade623c0564/src/lib/openapi/spec/sdk-context-schema.ts))**, generated type has issues like for example `Property 'remoteAddress' of type 'string | undefined' is not assignable to 'string' index type 'string'.` because of index type `[key: string]: string;`.

Is there a way of making it work with TypeScript?

#### More details

From schema JSON:
```
...
      "sdkContextSchema": {
        "description": "The Unleash context as modeled in client SDKs",
        "type": "object",
        "additionalProperties": {
          "type": "string",
          "example": "top-level custom context value"
        },
        "required": [
          "appName"
        ],
        "properties": {
          "appName": {
            "type": "string",
            "minLength": 1,
            "example": "My cool application."
          },
          "currentTime": {
            "type": "string",
            "format": "date-time",
            "example": "2022-07-05T12:56:41+02:00"
          },
          "environment": {
            "type": "string",
            "deprecated": true
          },
          "properties": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            },
            "example": {
              "customContextField": "this is one!",
              "otherCustomField": "3"
            }
          },
...
        }
      },
...
```

I get output like so:
```
/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.15.1
 */
import type { SdkContextSchemaProperties } from './sdkContextSchemaProperties';

/**
 * The Unleash context as modeled in client SDKs
 */
export interface SdkContextSchema {
  appName: string;
  currentTime?: string;
  /** @deprecated */
  environment?: string;
  properties?: SdkContextSchemaProperties;
  remoteAddress?: string;
  sessionId?: string;
  userId?: string;
  [key: string]: string;
}
```

</div>

**Comment by Tymek** [comment]
Relevant code: https://github.com/anymaniax/orval/blob/f3928e184e9e44e686162e2eda194092e8a564ac/src/core/getters/object.ts#L104

**Comment by anymaniax** [comment]
sure for PR but I am not just that just transform it to any is a good solution tho

**Comment by Tymek** [comment]
Right. Even `resolvedValue.value | <other types from properties>` is not strictly correct.

Only way I know to make this work is to switch to [Intersection Types](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#intersection-types), but that will export `type` instead of `interface`..

**Comment by michinger** [comment]
having the same issue

**Comment by melloware** [comment]
I am getting key of unknown when I use additional properties and everything is working. Is this still an issue?

**Comment by PedroPerpetua** [comment]
> I am getting key of unknown when I use additional properties and everything is working. Is this still an issue?

With Orval 7.7.0 and typescript 5.8.2 I'm still getting issues.

`Property ''<property name>'' of type '<Generated type> | undefined' is not assignable to 'string' index type '{ [key: string]: unknown; }'.`

This for a schema that defines as follows:
```yml
# ...
schema:
  properties:
    # ...
        additionalProperties:
          type: object
        properties:
          <property name>:
            # ...
              title: <Generated Type origin>
```

**Comment by melloware** [comment]
Oh i see I just have `addtionalProperties:true`

```yml
HttpProblem:
      description: HTTP Problem Response according to RFC9457 & RFC7807
      additionalProperties: true
      type: object
      properties:
        type:
          type: string
          format: uri
          description: A optional URI reference that identifies the problem type
          examples:
          - https://example.com/errors/not-found
        title:
          type: string
          description: "A optional, short, human-readable summary of the problem type"
          examples:
          - Not Found
        status:
          type: integer
          format: int32
          description: The HTTP status code for this occurrence of the problem
          examples:
          - 404
        detail:
          type: string
          description: A optional human-readable explanation specific to this occurrence
            of the problem
          examples:
          - Record not found
        instance:
          type: string
          format: uri
          description: A URI reference that identifies the specific occurrence of
            the problem
          examples:
          - https://api.example.com/errors/123
  ```

And it generates correctly for me but your use case is different i see now the `[key: string]: unknown;` works for me because its juts addtional properties in the payload...

```js
/**
 * HTTP Problem Response according to RFC9457 & RFC7807
 */
export interface HttpProblem {
	/** A optional URI reference that identifies the problem type */
	type?: string;
	/** A optional, short, human-readable summary of the problem type */
	title?: string;
	/** The HTTP status code for this occurrence of the problem */
	status?: number;
	/** A optional human-readable explanation specific to this occurrence of the problem */
	detail?: string;
	/** A URI reference that identifies the specific occurrence of the problem */
	instance?: string;
	[key: string]: unknown;
}
```
