### ISSUE TITLE
Non unique enum names with `-` and `+` prefixes

### ISSUE THREAD

**Issue by gervaisb** [anymaniax/orval#638]
## What are the steps to reproduce this issue?

1. Add an enumeration with two values that vary only with the `-` and `+` prefixes:

```
        - in: query
          name: sort
          required: false
          description: >
            The property to sort on. Direction is ascending by default. To 
            indicate descending, prefix property with `-`
          schema:
            type: string
            enum:
              - date
              - -date
```

## What happens?

Those special characters are ignored and the keys are identical:

```
  export const MyOperationSort = {
    date: '-date' as MyOperationSort,
    date: 'date' as MyOperationSort,
  };
```

## What were you expecting to happen?

The special characters are escaped so that we can use the enumeration.

## Any other comments?

This issue has been discovered while using the `-` and `+` convention to define the direction on a sorting parameter. It has been reported on the guideline owner too: https://github.com/belgif/rest-guide/issues/98
