### ISSUE TITLE
Null in Enum

### ISSUE THREAD

**Issue by mitsuru-kasai** [anymaniax/orval#686]
## What are the steps to reproduce this issue?

1. Make OpenAPI Spec with schemas of Enum containing `null`
2. Execute `orval`
3. Broken schema file is generated

Reproduction code is here
https://github.com/mitsuru-kasai/orval-null-in-enum

## What happens?

When I input openapi spec with schemas of Enum containing `null`, broken schema file is outputted.

For example, with schema
```
    Foo:
      type: number
      nullable: true
      enum:
        - null
```

then following schema is outputted
```typescript
export type Foo = typeof Foo[keyof typeof Foo];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Foo = {
  '': ,
} as const;
```

Nullable schema is valid in Openapi 3.0 (see [here](https://swagger.io/docs/specification/data-models/enums/))

## What were you expecting to happen?

A valid schema file is outputted, for example
```typescript

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Foo = {
  '_NULL': null,
} as const;
```

I am not confident whether it is ok to use 'null' as the enum key because the key conflicts when both `null` and `'null'`(string)  are contained in single enum.

## Any logs, error output, etc?

nothing

## Any other comments?

Thank everyone for development of this awesome library!
I love `orval` ;)

## What versions are you using?

**Operating System:** macOS 12.3.1
**Package Version:** orval 6.10.3
**Browser Version:** Chrome 107.0.5304.110

**Comment by mitsuru-kasai** [comment]
I found the potentially related issue #310

**Comment by anymaniax** [comment]
hello @mitsuru-kasai, can you test with `orval@alpha`

**Comment by anymaniax** [comment]
You can use also `x-enumNames` in your specification with the alpha

**Comment by bigen1925** [comment]
@anymaniax 
Thank you for the comment. :)

I tried `orval@alpha`, but didn't worked.
The same schema was outputted.

I also tried `x-enumNames`, but didn't worked.
With spec
```yaml
  schemas:
    Foo:
      type: number
      nullable: true
      x-enumNames:
        - "1"
        - "null"
      enum:
        - 1
        - null
```
, output was this
```typescript
export type Foo = typeof Foo[keyof typeof Foo];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Foo = {
  '1': 1,
  null: ,
} as const;
```

**Comment by mitsuru-kasai** [comment]
@anymaniax 
Thank you for the comment. :)

I tried `orval@alpha`, but didn't worked.
The same schema was outputted.

I also tried `x-enumNames`, but didn't worked.
With spec
```yaml
  schemas:
    Foo:
      type: number
      nullable: true
      x-enumNames:
        - "1"
        - "null"
      enum:
        - 1
        - null
```
, output was this
```typescript
export type Foo = typeof Foo[keyof typeof Foo];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Foo = {
  '1': 1,
  null: ,
} as const;
```
