### ISSUE TITLE
`anyOf` properties break generated msw mocks

### ISSUE THREAD

**Issue by invakid404** [anymaniax/orval#755]
## What are the steps to reproduce this issue?

1. Pick any sample from the orval repo, e.g. `basic`
2. Pick any schema (e.g. `Pet`) and add a new property to it that uses `anyOf`, e.g.:
```yaml
        dummy:
          anyOf:
            - type: string
              format: hostname
            - type: string
              format: ipv4
            - type: string
              format: ipv6
```
3. Run orval
4. Check the generated `./api/endpoints/petstoreFromFileSpecWithTransformer.ts` file
5. Observe the errors

## What happens?

When using `anyOf`, orval decides to wrap the values it passes to `faker.arrayElement` in curly braces ({}) for whatever reason.

## What were you expecting to happen?

I was expecting the generated code for the array elements to not be wrapped in curly braces so that the produced code compiles.

## Any logs, error output, etc?

N/A

## Any other comments?

Happens on both on v6.11.1 and on master.

## What versions are you using?

**Operating System:** Linux (Funtoo next)
**Package Version:** v6.11.1
**Browser Version:** N/A
