### ISSUE TITLE
TS Error: argument of type 'number' is not assignable to parameter of type 'string | Blob'

### ISSUE THREAD

**Issue by chiptus** [anymaniax/orval#845]
Wow, this tool is amazing, it has everything we need to make types generation automatic (until now we did by hand when needed)

## What are the steps to reproduce this issue?
I have this schema:

```yaml
/endpoints:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - collectionFormat: csv
        description: List of tag identifiers to which this environment(endpoint) is
          associated
        in: formData
        items:
          type: integer
        name: TagIds
        type: array
```
## What happens?
![Screenshot_20230430_184400](https://user-images.githubusercontent.com/1381655/235351169-1267883e-658c-484b-a909-715843f4cf72.png)

…

## What were you expecting to happen?
no error. so code should probably be:

```ts
if (endpointCreateBody.TagIds !== undefined) {
    endpointCreateBody.TagIds.forEach((value) =>
      formData.append('TagIds', String(value))
    );
  }
```

## Any logs, error output, etc?
`Argument of type 'number' is not assignable to parameter of type 'string | Blob'`

## What versions are you using?

**Operating System:** ubuntu
**Package Version:** v6.15.0
**Browser Version:** not in browser
