### ISSUE TITLE
Support minimum array length constraint

### ISSUE THREAD

**Issue by rgupta33** [anymaniax/orval#880]
## What are the steps to reproduce this issue?

1. open api spec with this parameter: 
```
- in: query
        name: ids
        schema:
          type: array
          minItems: 1
          items:
            type: string
```

2. run orval on the spec

## What happens?

The minItems length constraint is not enforced in any way. 

## What were you expecting to happen?

I was expecting there to be some way to enforce that minimum length. Orval could possibly generate something like this to enforce the typing:

`type arrMin1Str = [string, ...string[]]; // The minimum is 1 string.`

## Any logs, error output, etc?

…

## Any other comments?

…

## What versions are you using?

**Operating System:** MacOS Ventura 13.2.1
**Package Version:** 6.16.0
**Browser Version:** 114.0.5735.106
