### ISSUE TITLE
Enums are parsed to invalid Typescript

### ISSUE THREAD

**Issue by vonkanehoffen** [anymaniax/orval#884]
## What are the steps to reproduce this issue?

1. `npm i` this minimal example repo: https://github.com/vonkanehoffen/orval-enum-bug-repro
2. Run `npm run codegen`

## What happens?

If you look in `generated/model/loginStatus.ts` you'll notice Orval has generated invalid syntax:
```
export const LoginStatus = {
  '0_-_Unknown': 0 - Unknown,
  '1_-_Success': 1 - Success,
  '2_-_TwoFactorRequiredYubikey': 2 - TwoFactorRequiredYubikey,
  '3_-_TwoFactorRequiredGoogleAuthenticator': 3 - TwoFactorRequiredGoogleAuthenticator,
  '4_-_InvalidEmailOrPassword': 4 - InvalidEmailOrPassword,
  '5_-_InvalidToken': 5 - InvalidToken,
  '6_-_InvalidRefreshToken': 6 - InvalidRefreshToken,
  '7_-_InvalidTwoFactorCode': 7 - InvalidTwoFactorCode,
} as const;
```

This is from a valid schema:
```
components:
  schemas:
    LoginStatus:
      enum:
        - 0 - Unknown
        - 1 - Success
        - 2 - TwoFactorRequiredYubikey
        - 3 - TwoFactorRequiredGoogleAuthenticator
        - 4 - InvalidEmailOrPassword
        - 5 - InvalidToken
        - 6 - InvalidRefreshToken
        - 7 - InvalidTwoFactorCode
      type: integer
      format: int32
```
(this is part of a schema originally generated by Swashbockle in .Net)

## What were you expecting to happen?

I'd expect the generation to be something like:

```
export const LoginStatus = {
  '0_-_Unknown': 0 ,
  '1_-_Success': 1,
  '2_-_TwoFactorRequiredYubikey': 2,
  '3_-_TwoFactorRequiredGoogleAuthenticator': 3,
  '4_-_InvalidEmailOrPassword': 4,
  '5_-_InvalidToken': 5,
  '6_-_InvalidRefreshToken': 6,
  '7_-_InvalidTwoFactorCode': 7,
} as const;
```

## Any logs, error output, etc?

…

## Any other comments?

The OpenAPI spec is a bit vague around enum from what I could find. The example passes validation but is there some other way it should look to fix this?

## What versions are you using?

**Operating System:** Masc OS Ventura
**Package Version:** 6.16.0
**Browser Version:** N/A
