### ISSUE TITLE
Nullable objects are missing ` | null`

### ISSUE THREAD

**Issue by karlismelderis-mckinsey** [anymaniax/orval#981]
## What are the steps to reproduce this issue?

Have an Open API 3.0 API spec with such key:
```yaml
          "example": {
            "type": "object",
            "description": "example of nullable object",
            "nullable": true
          },
```

## What happens?

final result has type with required key:
```
...
 example: SomeType;
...
```

## What were you expecting to happen?

```
...
 example: SomeType | null;
...
```

## Any logs, error output, etc?

I managed to narrow down issue to this location:
https://github.com/anymaniax/orval/blob/master/packages/core/src/resolvers/object.ts#L7

## What versions are you using?

**Package Version:** 6.19.1
